export const ERROR_CODES = {
  ROUTER_NO_PROVIDER: 'ROUTER_NO_PROVIDER',
  ROUTER_TIMEOUT: 'ROUTER_TIMEOUT',
  ROUTER_RATE_LIMITED: 'ROUTER_RATE_LIMITED',
  BILLING_QUOTA_EXCEEDED: 'BILLING_QUOTA_EXCEEDED',
  BILLING_SUBSCRIPTION_INACTIVE: 'BILLING_SUBSCRIPTION_INACTIVE',
  INSTANCE_NOT_FOUND: 'INSTANCE_NOT_FOUND',
  INSTANCE_PROVISIONING: 'INSTANCE_PROVISIONING',
  AUTH_INVALID_CREDENTIALS: 'AUTH_INVALID_CREDENTIALS',
  BIND_CODE_INVALID: 'BIND_CODE_INVALID',
} as const;

export type ErrorCode = (typeof ERROR_CODES)[keyof typeof ERROR_CODES];
