/**
 * Top 100 OpenClaw Skills 库
 * 可扩展，持续提供新 skill 给 1Claw 用户选择
 * isPreinstalled: true 的为预装（首发套餐默认包含）
 */
export const SKILLS_SEED = [
  // === 预装首发 (isPreinstalled: true, sortOrder 0-19) ===
  { slug: 'memory-core', nameZh: 'Memory Core（长期记忆）', nameEn: 'Memory Core', category: 'memory', isPreinstalled: true, sortOrder: 0 },
  { slug: 'soul-profile', nameZh: 'Soul Profile（人格风格）', nameEn: 'Soul Profile', category: 'memory', isPreinstalled: true, sortOrder: 1 },
  { slug: 'daily-briefing', nameZh: 'Daily Briefing（日报简报）', nameEn: 'Daily Briefing', category: 'productivity', isPreinstalled: true, sortOrder: 2 },
  { slug: 'meeting-notes', nameZh: 'Meeting Notes（会议记录）', nameEn: 'Meeting Notes', category: 'productivity', isPreinstalled: true, sortOrder: 3 },
  { slug: 'web-research', nameZh: 'Web Research（网页研究）', nameEn: 'Web Research', category: 'research', isPreinstalled: true, sortOrder: 4 },
  { slug: 'content-drafting', nameZh: 'Content Drafting（内容起草）', nameEn: 'Content Drafting', category: 'writing', isPreinstalled: true, sortOrder: 5 },
  { slug: 'email-copilot', nameZh: 'Email Copilot（邮件助手）', nameEn: 'Email Copilot', category: 'writing', isPreinstalled: true, sortOrder: 6 },
  { slug: 'crm-update', nameZh: 'CRM Update（客户信息更新）', nameEn: 'CRM Update', category: 'sales', isPreinstalled: true, sortOrder: 7 },
  { slug: 'knowledge-base-qa', nameZh: 'Knowledge Base Q&A（知识库问答）', nameEn: 'Knowledge Base Q&A', category: 'research', isPreinstalled: true, sortOrder: 8 },
  { slug: 'social-reply', nameZh: 'Social Reply Assistant（社媒回复）', nameEn: 'Social Reply Assistant', category: 'writing', isPreinstalled: true, sortOrder: 9 },
  { slug: 'task-planner', nameZh: 'Task Planner（任务规划）', nameEn: 'Task Planner', category: 'productivity', isPreinstalled: true, sortOrder: 10 },
  { slug: 'automation-runner', nameZh: 'Automation Runner（自动化执行）', nameEn: 'Automation Runner', category: 'productivity', isPreinstalled: true, sortOrder: 11 },
  { slug: 'seo-optimization', nameZh: 'SEO Optimization（SEO 优化）', nameEn: 'SEO Optimization', category: 'dev', isPreinstalled: true, sortOrder: 12 },
  { slug: 'notion-sync', nameZh: 'Notion Sync（Notion 同步）', nameEn: 'Notion Sync', category: 'productivity', isPreinstalled: true, sortOrder: 13 },
  { slug: 'github-issue-helper', nameZh: 'GitHub Issue Helper（Issue 助手）', nameEn: 'GitHub Issue Helper', category: 'dev', isPreinstalled: true, sortOrder: 14 },
  // === 扩展技能 (sortOrder 20+) ===
  { slug: 'figma-implement', nameZh: 'Figma 设计转代码', nameEn: 'Figma Design to Code', category: 'dev', isPreinstalled: false, sortOrder: 20 },
  { slug: 'vercel-deploy', nameZh: 'Vercel 部署', nameEn: 'Vercel Deploy', category: 'dev', isPreinstalled: false, sortOrder: 21 },
  { slug: 'gh-address-comments', nameZh: 'GitHub PR 评论处理', nameEn: 'GitHub PR Comments', category: 'dev', isPreinstalled: false, sortOrder: 22 },
  { slug: 'notion-meeting-intel', nameZh: 'Notion 会议智能', nameEn: 'Notion Meeting Intelligence', category: 'productivity', isPreinstalled: false, sortOrder: 23 },
  { slug: 'code-review', nameZh: 'Code Review（代码审查）', nameEn: 'Code Review', category: 'dev', isPreinstalled: false, sortOrder: 24 },
  { slug: 'doc-gen', nameZh: 'Doc Gen（文档生成）', nameEn: 'Documentation Generator', category: 'dev', isPreinstalled: false, sortOrder: 25 },
  { slug: 'test-gen', nameZh: 'Test Gen（测试生成）', nameEn: 'Test Generator', category: 'dev', isPreinstalled: false, sortOrder: 26 },
  { slug: 'refactor-assistant', nameZh: 'Refactor Assistant（重构助手）', nameEn: 'Refactor Assistant', category: 'dev', isPreinstalled: false, sortOrder: 27 },
  { slug: 'bug-analyzer', nameZh: 'Bug Analyzer（Bug 分析）', nameEn: 'Bug Analyzer', category: 'dev', isPreinstalled: false, sortOrder: 28 },
  { slug: 'api-doc', nameZh: 'API Doc（API 文档）', nameEn: 'API Documentation', category: 'dev', isPreinstalled: false, sortOrder: 29 },
  { slug: 'translation', nameZh: 'Translation（多语言翻译）', nameEn: 'Translation', category: 'writing', isPreinstalled: false, sortOrder: 30 },
  { slug: 'summarizer', nameZh: 'Summarizer（摘要生成）', nameEn: 'Summarizer', category: 'writing', isPreinstalled: false, sortOrder: 31 },
  { slug: 'blog-writer', nameZh: 'Blog Writer（博客写作）', nameEn: 'Blog Writer', category: 'writing', isPreinstalled: false, sortOrder: 32 },
  { slug: 'copywriter', nameZh: 'Copywriter（文案撰写）', nameEn: 'Copywriter', category: 'writing', isPreinstalled: false, sortOrder: 33 },
  { slug: 'press-release', nameZh: 'Press Release（新闻稿）', nameEn: 'Press Release', category: 'writing', isPreinstalled: false, sortOrder: 34 },
  { slug: 'calendar-sync', nameZh: 'Calendar Sync（日历同步）', nameEn: 'Calendar Sync', category: 'productivity', isPreinstalled: false, sortOrder: 35 },
  { slug: 'reminder', nameZh: 'Reminder（提醒助手）', nameEn: 'Reminder', category: 'productivity', isPreinstalled: false, sortOrder: 36 },
  { slug: 'time-tracker', nameZh: 'Time Tracker（时间追踪）', nameEn: 'Time Tracker', category: 'productivity', isPreinstalled: false, sortOrder: 37 },
  { slug: 'project-status', nameZh: 'Project Status（项目周报）', nameEn: 'Project Status Report', category: 'productivity', isPreinstalled: false, sortOrder: 38 },
  { slug: 'one-on-one', nameZh: 'One-on-One（1:1 模板）', nameEn: 'One-on-One Template', category: 'productivity', isPreinstalled: false, sortOrder: 39 },
  { slug: 'retrospective', nameZh: 'Retrospective（复盘模板）', nameEn: 'Retrospective Template', category: 'productivity', isPreinstalled: false, sortOrder: 40 },
  { slug: 'sprint-planning', nameZh: 'Sprint Planning（迭代规划）', nameEn: 'Sprint Planning', category: 'productivity', isPreinstalled: false, sortOrder: 41 },
  { slug: 'brainstorm', nameZh: 'Brainstorm（头脑风暴）', nameEn: 'Brainstorming', category: 'productivity', isPreinstalled: false, sortOrder: 42 },
  { slug: 'decision-meeting', nameZh: 'Decision Meeting（决策会议）', nameEn: 'Decision Meeting Prep', category: 'productivity', isPreinstalled: false, sortOrder: 43 },
  { slug: 'market-research', nameZh: 'Market Research（市场调研）', nameEn: 'Market Research', category: 'research', isPreinstalled: false, sortOrder: 44 },
  { slug: 'competitor-analysis', nameZh: 'Competitor Analysis（竞品分析）', nameEn: 'Competitor Analysis', category: 'research', isPreinstalled: false, sortOrder: 45 },
  { slug: 'data-extract', nameZh: 'Data Extract（数据提取）', nameEn: 'Data Extraction', category: 'research', isPreinstalled: false, sortOrder: 46 },
  { slug: 'rss-digest', nameZh: 'RSS Digest（资讯摘要）', nameEn: 'RSS Digest', category: 'research', isPreinstalled: false, sortOrder: 47 },
  { slug: 'lead-scoring', nameZh: 'Lead Scoring（线索评分）', nameEn: 'Lead Scoring', category: 'sales', isPreinstalled: false, sortOrder: 48 },
  { slug: 'sales-email', nameZh: 'Sales Email（销售邮件）', nameEn: 'Sales Email Assistant', category: 'sales', isPreinstalled: false, sortOrder: 49 },
  { slug: 'follow-up', nameZh: 'Follow-up（跟进提醒）', nameEn: 'Follow-up Reminder', category: 'sales', isPreinstalled: false, sortOrder: 50 },
  { slug: 'pipeline-report', nameZh: 'Pipeline Report（漏斗报告）', nameEn: 'Pipeline Report', category: 'sales', isPreinstalled: false, sortOrder: 51 },
  { slug: 'customer-insight', nameZh: 'Customer Insight（客户洞察）', nameEn: 'Customer Insight', category: 'sales', isPreinstalled: false, sortOrder: 52 },
  { slug: 'slack-summary', nameZh: 'Slack Summary（Slack 摘要）', nameEn: 'Slack Summary', category: 'productivity', isPreinstalled: false, sortOrder: 53 },
  { slug: 'discord-mod', nameZh: 'Discord Mod（Discord 管理）', nameEn: 'Discord Moderation', category: 'community', isPreinstalled: false, sortOrder: 54 },
  { slug: 'faq-bot', nameZh: 'FAQ Bot（FAQ 机器人）', nameEn: 'FAQ Bot', category: 'support', isPreinstalled: false, sortOrder: 55 },
  { slug: 'ticket-triage', nameZh: 'Ticket Triage（工单分拣）', nameEn: 'Ticket Triage', category: 'support', isPreinstalled: false, sortOrder: 56 },
  { slug: 'onboarding-flow', nameZh: 'Onboarding Flow（入职流程）', nameEn: 'Onboarding Flow', category: 'hr', isPreinstalled: false, sortOrder: 57 },
  { slug: 'job-description', nameZh: 'Job Description（职位描述）', nameEn: 'Job Description', category: 'hr', isPreinstalled: false, sortOrder: 58 },
  { slug: 'interview-prep', nameZh: 'Interview Prep（面试准备）', nameEn: 'Interview Prep', category: 'hr', isPreinstalled: false, sortOrder: 59 },
  { slug: 'contract-draft', nameZh: 'Contract Draft（合同起草）', nameEn: 'Contract Draft', category: 'legal', isPreinstalled: false, sortOrder: 60 },
  { slug: 'nda-review', nameZh: 'NDA Review（NDA 审阅）', nameEn: 'NDA Review', category: 'legal', isPreinstalled: false, sortOrder: 61 },
  { slug: 'expense-report', nameZh: 'Expense Report（费用报销）', nameEn: 'Expense Report', category: 'finance', isPreinstalled: false, sortOrder: 62 },
  { slug: 'invoice-draft', nameZh: 'Invoice Draft（发票起草）', nameEn: 'Invoice Draft', category: 'finance', isPreinstalled: false, sortOrder: 63 },
  { slug: 'sql-helper', nameZh: 'SQL Helper（SQL 助手）', nameEn: 'SQL Helper', category: 'dev', isPreinstalled: false, sortOrder: 64 },
  { slug: 'regex-helper', nameZh: 'Regex Helper（正则助手）', nameEn: 'Regex Helper', category: 'dev', isPreinstalled: false, sortOrder: 65 },
  { slug: 'yaml-validator', nameZh: 'YAML Validator（YAML 校验）', nameEn: 'YAML Validator', category: 'dev', isPreinstalled: false, sortOrder: 66 },
  { slug: 'json-formatter', nameZh: 'JSON Formatter（JSON 格式化）', nameEn: 'JSON Formatter', category: 'dev', isPreinstalled: false, sortOrder: 67 },
  { slug: 'mermaid-gen', nameZh: 'Mermaid Gen（流程图生成）', nameEn: 'Mermaid Diagram', category: 'dev', isPreinstalled: false, sortOrder: 68 },
  { slug: 'prompt-optimizer', nameZh: 'Prompt Optimizer（提示词优化）', nameEn: 'Prompt Optimizer', category: 'ai', isPreinstalled: false, sortOrder: 69 },
  { slug: 'model-selector', nameZh: 'Model Selector（模型选择）', nameEn: 'Model Selector', category: 'ai', isPreinstalled: false, sortOrder: 70 },
  { slug: 'rag-builder', nameZh: 'RAG Builder（RAG 构建）', nameEn: 'RAG Builder', category: 'ai', isPreinstalled: false, sortOrder: 71 },
  { slug: 'embedding-helper', nameZh: 'Embedding Helper（向量化助手）', nameEn: 'Embedding Helper', category: 'ai', isPreinstalled: false, sortOrder: 72 },
  { slug: 'image-alt-text', nameZh: 'Image Alt Text（图片描述）', nameEn: 'Image Alt Text', category: 'accessibility', isPreinstalled: false, sortOrder: 73 },
  { slug: 'accessibility-audit', nameZh: 'Accessibility Audit（无障碍审计）', nameEn: 'Accessibility Audit', category: 'accessibility', isPreinstalled: false, sortOrder: 74 },
  { slug: 'security-scan', nameZh: 'Security Scan（安全扫描）', nameEn: 'Security Scan', category: 'dev', isPreinstalled: false, sortOrder: 75 },
  { slug: 'dependency-audit', nameZh: 'Dependency Audit（依赖审计）', nameEn: 'Dependency Audit', category: 'dev', isPreinstalled: false, sortOrder: 76 },
  { slug: 'changelog-gen', nameZh: 'Changelog Gen（变更日志）', nameEn: 'Changelog Generator', category: 'dev', isPreinstalled: false, sortOrder: 77 },
  { slug: 'release-notes', nameZh: 'Release Notes（发布说明）', nameEn: 'Release Notes', category: 'dev', isPreinstalled: false, sortOrder: 78 },
  { slug: 'readme-gen', nameZh: 'README Gen（README 生成）', nameEn: 'README Generator', category: 'dev', isPreinstalled: false, sortOrder: 79 },
  { slug: 'git-commit', nameZh: 'Git Commit（提交信息）', nameEn: 'Git Commit Message', category: 'dev', isPreinstalled: false, sortOrder: 80 },
  { slug: 'pr-description', nameZh: 'PR Description（PR 描述）', nameEn: 'PR Description', category: 'dev', isPreinstalled: false, sortOrder: 81 },
  { slug: 'slack-integration', nameZh: 'Slack Integration（Slack 集成）', nameEn: 'Slack Integration', category: 'productivity', isPreinstalled: false, sortOrder: 82 },
  { slug: 'teams-sync', nameZh: 'Teams Sync（Teams 同步）', nameEn: 'Teams Sync', category: 'productivity', isPreinstalled: false, sortOrder: 83 },
  { slug: 'feishu-bot', nameZh: 'Feishu Bot（飞书机器人）', nameEn: 'Feishu Bot', category: 'productivity', isPreinstalled: false, sortOrder: 84 },
  { slug: 'dingtalk-bot', nameZh: 'DingTalk Bot（钉钉机器人）', nameEn: 'DingTalk Bot', category: 'productivity', isPreinstalled: false, sortOrder: 85 },
  { slug: 'wechat-bot', nameZh: 'WeChat Bot（微信机器人）', nameEn: 'WeChat Bot', category: 'productivity', isPreinstalled: false, sortOrder: 86 },
  { slug: 'telegram-bot', nameZh: 'Telegram Bot（Telegram 机器人）', nameEn: 'Telegram Bot', category: 'productivity', isPreinstalled: false, sortOrder: 87 },
  { slug: 'whatsapp-bot', nameZh: 'WhatsApp Bot（WhatsApp 机器人）', nameEn: 'WhatsApp Bot', category: 'productivity', isPreinstalled: false, sortOrder: 88 },
  { slug: 'linkedin-helper', nameZh: 'LinkedIn Helper（领英助手）', nameEn: 'LinkedIn Helper', category: 'writing', isPreinstalled: false, sortOrder: 89 },
  { slug: 'twitter-helper', nameZh: 'Twitter Helper（X 助手）', nameEn: 'Twitter Helper', category: 'writing', isPreinstalled: false, sortOrder: 90 },
  { slug: 'product-spec', nameZh: 'Product Spec（产品规格）', nameEn: 'Product Spec', category: 'product', isPreinstalled: false, sortOrder: 91 },
  { slug: 'user-story', nameZh: 'User Story（用户故事）', nameEn: 'User Story', category: 'product', isPreinstalled: false, sortOrder: 92 },
  { slug: 'roadmap-draft', nameZh: 'Roadmap Draft（路线图）', nameEn: 'Roadmap Draft', category: 'product', isPreinstalled: false, sortOrder: 93 },
  { slug: 'feature-request', nameZh: 'Feature Request（需求分析）', nameEn: 'Feature Request Analysis', category: 'product', isPreinstalled: false, sortOrder: 94 },
  { slug: 'api-design', nameZh: 'API Design（API 设计）', nameEn: 'API Design', category: 'dev', isPreinstalled: false, sortOrder: 95 },
  { slug: 'db-schema', nameZh: 'DB Schema（数据库设计）', nameEn: 'DB Schema Design', category: 'dev', isPreinstalled: false, sortOrder: 96 },
  { slug: 'docker-compose', nameZh: 'Docker Compose（容器编排）', nameEn: 'Docker Compose', category: 'dev', isPreinstalled: false, sortOrder: 97 },
  { slug: 'ci-cd-config', nameZh: 'CI/CD Config（流水线配置）', nameEn: 'CI/CD Config', category: 'dev', isPreinstalled: false, sortOrder: 98 },
  { slug: 'skill-creator', nameZh: 'Skill Creator（技能创建器）', nameEn: 'Skill Creator', category: 'ai', isPreinstalled: false, sortOrder: 99 },
];
